### ISSUE TITLE
Should appraisal generate Ruby 2 syntax?

### ISSUE THREAD

**Issue by tute** [thoughtbot/appraisal#105]
thoughtbot guides favor the use of Ruby 2 hash syntax. Appraisal generates arrow syntax (for example:
https://github.com/thoughtbot/paperclip/pull/1976/files#diff-4739e40ecb83ba072e395f63cca12703R5).

Should it generate Ruby 2 hash syntax instead?

**Comment by sikachu** [comment]
Appraisal still supports Ruby 1.8.7, so why we create the old hash version by default. With that said, I don't mind accepting a PR which updates https://github.com/thoughtbot/appraisal/blob/master/lib/appraisal/utils.rb#L8 to print out new syntax version if it's running on Ruby 1.9+ though. I think `stub_const` RUBY_VERSION should be a good way to test it.

**Comment by tute** [comment]
This makes sense, it's not worth it for me right now. Thanks, Prem!

**Comment by fosberyi** [comment]
Hey @sikachu, I saw @tute posted this a while back and thought I'd take a crack at it. I used `stub_const` on `RUBY_VERSION` like you suggested. I've got all the unit tests passing, but the larger acceptance tests involving generations of files and testing contents always use the system Ruby. So stubbing the constant doesn't seem to work.

Wanted to see if either of you guys had any suggestions:

https://github.com/fosberyi/appraisal/tree/add_ruby_2_syntax

Thanks!

**Comment by sikachu** [comment]
@fosberyi thanks for taking a crack at this!

**Comment by sikachu** [comment]
For acceptance test, maybe we might want to start using fixture or something and make it load expected generated result for the right `RUBY_VERSION`. It's annoying having to maintain two files for each test result, but that's probably okay.

For the implementation, I think updating https://github.com/thoughtbot/appraisal/blob/4df6acaec0e6dfce04afd216fb091a705aada7ab/lib/appraisal/utils.rb#L8-L23 should be enough for it to generate Ruby 1.9 hash syntax.

**Comment by fosberyi** [comment]
@sikachu Yeah no problem!

I think I see what you mean for the fixtures. And then we would break https://github.com/thoughtbot/appraisal/blob/4df6acaec0e6dfce04afd216fb091a705aada7ab/spec/acceptance/appraisals_file_bundler_dsl_compatibility_spec.rb into two tests, one >=1.9 and one <, right?

As far as implementation, I think I've already got it here: https://github.com/fosberyi/appraisal/blob/add_ruby_2_syntax/lib/appraisal/utils.rb#L8-L31 - I just extracted that conditional to it's own method to keep that first method smaller. Also, is there any reason that's a `case` statement and not just an `if`?

Let me know and I'll see if I can get it all working, thanks!

**Comment by fosberyi** [comment]
@sikachu ok, I think I got it - just submitted a PR. Didn't need to really do a full fixture, just added a helper method that determines what `path: ....` should look like by checking the Ruby version. Because we're running the suite against multiple versions, it'll run differently in 1.8 vs >= 1.9.

One last issue is the build for 1.8 is erroring because it's trying to install Rake ~>11 but that version of rake requires Ruby >=1.9. Should we add rake 10 to that block in the Gemfile? (Feel free to move this convo to the PR).

Thanks!

**Comment by philsturgeon** [comment]
Ha, just ran into this. I've had to mess about getting Travis use the normal Gemfile and specifically include extra jobs for the Ruby 2.0+ versions... https://github.com/typhoeus/typhoeus/pull/583/files#diff-354f30a63fb0907d4ad57269548329e3R24

I'd like to avoid doing this in the future. Can we just have an arrow function in there?
