### ISSUE TITLE
support for appraisal install ---without

### ISSUE THREAD

**Issue by bertBruynooghe** [thoughtbot/appraisal#108]
It would be nice to have the option to leave out the development group from the generated gemfiles.

Some explanation:
the gem I'm working on should work with and without Rails, so I need to run tests without rails, and with Rails. Since ```install``` always copies the whole content of the root ```Gemfile```, it means that this one cannot include Rails. However, that also means that I can't run the rails command anymore on the ```spec/dummy``` Rails project.
Having the possibility to express: ```appraisal install --without development``` would allow me to keep all gemfiles in sync with each other...

**Comment by sikachu** [comment]
@bertBruynooghe this flag will just being passed to Bundler, right? I think we might be able to do that.

**Comment by bertBruynooghe** [comment]
I was rather thinking about removing the mentioned groups from the generated gemfiles, but being able to pass through to bundler might indeed also wok around the problem.

I guess you mean something like ``` appraisal --without development rspec ```, aren't you?

**Comment by sikachu** [comment]
Yes. As we're calling `bundle install` in the background as well I think it's best to pass that flag to Bundler and let Bundler does its thing.

Also, given that it's a remembered option (a.k.a. Bundler will create `.bundle/config` with `BUNDLE_WITHOUT` variable) if you ever run `appraisal install --without development` then you shouldn't need that `--without` flag when you run `appraisal rspec`.

**Comment by sikachu** [comment]
I just implemented this in e07ef279a12380530df9dc334952e1fc6e0f8615. I'm not sure if Bundler saves the `--without` option if you run `bundle install` with `--gemfile` command, but we can revisit that if that's not the case.
