### ISSUE TITLE
cannot interrupt  appraisal spec through SIG_TERM

### ISSUE THREAD

**Issue by bertBruynooghe** [thoughtbot/appraisal#109]
Ctrl-C does not work...

**Comment by sikachu** [comment]
@bertBruynooghe I was able to ctrl+c thoughtbot/paperclip test suite (that is also using Appraisal). Is your project actually public so I can see what's going on and if we should add any signal trap to it? Thanks!

**Comment by bertBruynooghe** [comment]
Unfortunately, the project is private. I'll keep the thread in my TODO list, and will try to recreate the situation on a public github project somewhere in the coming weeks.

**Comment by sikachu** [comment]
I'm going to close this for now due to inactivity. If you still able to reproduce the problem, please let me know so I can reopen the issue.
