### ISSUE TITLE
Should support `gem "foo" ref: "bar"`

### ISSUE THREAD

**Issue by jaredbeck** [thoughtbot/appraisal#119]
appraisal 2.1.0, ruby 2.3.1, bundler 1.12.5

**Input:**

```
# Appraisals
appraise "banana" do
  gem "rack-protection", github: "sinatra/rack-protection", ref: "7e723a74763bb83989d12"
end
```

**Expected output:**

```
# banana.gemfile
gem "rack-protection", :github => "sinatra/rack-protection", :ref => "7e723a74763bb83989d12"
```

**Current output:**

```
# banana.gemfile
gem "rack-protection", :github => "sinatra/rack-protection" # no ref
```

Appraisal seems to discard the `ref` option.

Documentation for the `ref` option can be found at http://bundler.io/git.html

Thanks for a great tool, this is the first issue I've had with it after almost a year of use! :heart:

**Comment by sikachu** [comment]
@jaredbeck sorry for the late response. I tried to reproduce your problem in https://github.com/sikachu/appraisal-git-ref-demo and it seems like everything is working as expected (as you can see from the generated Gemfile)

I don't think Appraisal is doing anything with any of the arguments that is passing to `gem` directive. Do you mind running `appraisal generate` again to see if you get the expected output?

**Comment by jaredbeck** [comment]
Thanks, Prem. I can't reproduce this anymore, either.
