### ISSUE TITLE
Don't know how to build task 'appraisal'

### ISSUE THREAD

**Issue by jvenezia** [thoughtbot/appraisal#120]
I can't run appraisal as a rake task.

I added appraisal as a development dependency in my gemspec : 
`spec.add_development_dependency 'appraisal', '~> 2.1'`

`appraisal rake` works great, but not `rake appraisal`.

**Comment by jvenezia** [comment]
Actually it works when adding `require 'appraisal'` into the rakefile.

**Comment by sikachu** [comment]
There's a chance that `rake appraisal` will go away pretty soon though, as we moved away from being a rake task to a command that use to run other command. So, `appraisal rake` would be the correct way to run it going forward and you could have the default rake task to be whatever you want.

**Comment by jvenezia** [comment]
Seems ok to me :)
Thanks!
