### ISSUE TITLE
`appraisal stick` to export BUNDLE_GEMFILE

### ISSUE THREAD

**Issue by printercu** [thoughtbot/appraisal#121]
Hi! I think it would be cool to be able to stick to specific env and run `rspec` and other commands without `appraisal %env%` prefix.

Currently I use `export BUNDLE_GEMFILE=./gemfiles/rails_5.gemfile` or just copy gemfile path from appraisal's output.

HDYT is it good idea to have `appraisal stick` to export and unset BUNDLE_GEMFILE?

**Comment by nickcharlton** [comment]
Hi @printercu!

My concern would be that you'd forget to undo it after running that. What do you think? Perhaps there should also be an `unstick` command?

**Comment by printercu** [comment]
Yep, `unstick` will be useful.

**Comment by nickcharlton** [comment]
Do you think you'd be able to have a go at contributing a PR for this?

**Comment by printercu** [comment]
I think I can, but it may take me about 2 weeks now.

**Comment by nickcharlton** [comment]
No worries! I'll keep an eye out for it.

**Comment by nickcharlton** [comment]
I'm going to close this as it's been stale for quite a while. Please re-open if it's something you'd still like to do!
