### ISSUE TITLE
IDE integration

### ISSUE THREAD

**Issue by atzorvas** [thoughtbot/appraisal#123]
I'm currently using RubyMine and I was wondering if anyone has fixed the runner in his IDE, and how, in order to run a specific spec or the whole suite from within the IDE.

Right now I'm using the following in order to run a specific spec
`bundle exec appraisal rspec path/to/spec/file_spec.rb`

**Comment by nickcharlton** [comment]
Hi @atzorvas!

I don't use RubyMine, but it sounds like you'd need to have specific integration for that. Is there an RSpec (or similar test) plugin that could be adapted, do you think?

**Comment by nickcharlton** [comment]
I'm going to close this as it's been quiet for a long time and it's not something I use. Please reopen this issue if it's still a problem for you!

**Comment by khun84** [comment]
@atzorvas i found a workaround for this.....Im using `appraisal (2.2.0)`

Just follow the steps outlined below:

1. Create a runner file say `spec_runner.rb` with the following content

```ruby
# !/usr/bin/env ruby

# Most of the code here is copied from /lib/appraisal/cli.rb in the appraisal gem library
require 'rubygems'
require 'bundler/setup'
require 'appraisal'
require 'appraisal/cli'

begin
 appraisal_name = ''rails-5.0" # this is just an example, use the appraisal that you have installed
  cmd = [appraisal_name, 'rspec'] + ARGV
  Appraisal::CLI.start(cmd)
rescue Appraisal::AppraisalsNotFound => e
  puts e.message
  exit 127
end
```

2. Open your **Run/Debug Configurations** in your Rubymine project. Then choose **Templates**  -> **Rspec**
3. Check the checkbox for **Use custom RSpec runner script**. The script file path should be `/path/to/spec_runner.rb`
4. Set the **Working directory** to your project root director.
5. Now run the any spec in Rubymine, your spec should be working now.

**Comment by roman-melnyk** [comment]
or just edit Rubimyne's configuration templates - Rspec - and add there an ENV variable
BUNDLE_GEMFILE=path_to_project/gemfiles/rails_7.0.gemfile # needed gemfile version
