### ISSUE TITLE
Generate gemfiles with Ruby 1.9 hash syntax

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/appraisal#140]
Appraisal generates Gemfiles with the older `:key => "value"` syntax. Is there a way to generate with the Ruby 1.9 `key: value` syntax instead?

**Comment by nickcharlton** [comment]
My understanding is that we've not updated the syntax as we still support older Rubies. At this point, we should drop those, switch to the new syntax and put out a new release. Would you be interested in helping with that?

**Comment by composerinteralia** [comment]
Oops I just realized this was addressed in https://github.com/thoughtbot/appraisal/commit/5fbd3539edf227e67ae8daeeaa0d467a44fe75ec. I just need to update to the latest version.
