### ISSUE TITLE
grep (used to ensure bundler availability) is not readily available on MS Windows

### ISSUE THREAD

**Issue by mlt** [thoughtbot/appraisal#146]
```
'grep' is not recognized as an internal or external command,
operable program or batch file.
>> Reinstall Bundler into C:/tools/Ruby24-x64/lib/ruby/gems/2.4.0
Successfully installed bundler-1.16.4
Parsing documentation for bundler-1.16.4
Done installing documentation for bundler after 7 seconds
1 gem installed
```
https://github.com/thoughtbot/appraisal/blob/5d1edf642091ca38f83cf2ae1cf9624fa23546c8/lib/appraisal/command.rb#L44

**Comment by nickcharlton** [comment]
I've not used Windows in many, many years, but I agree that this is something we should be better about.

Is there a solution to this which is similar in spirit but could be done easily enough?

Asking around, I had [`findstr`][1] suggested, which would mean we change that line to:

```sh
gem list -q "^bundler$" | findstr "bundler"
```

But this is not something I can test. What do you think?

[1]: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/findstr

**Comment by nickcharlton** [comment]
Perhaps a better solution is to just do this in Ruby:

```ruby
`gem list -q '^bundler'`.split(/\n/).any?
```

**Comment by nickcharlton** [comment]
I'm going to close this as #168 removes that reference of `grep`, which is nice!
