### ISSUE TITLE
getting File does not exist: minitest/rg after upgrading form old paradigm

### ISSUE THREAD

**Issue by jasonfb** [thoughtbot/appraisal#150]
I upgraded from the older paradigm of using Appraisal, in which I had specified Appraisal in a Gemfile that was in a folder at the same level of my ```gemfile/``` folder (was this a mistake?)

In any event, I added to specifying in my ```.gemspec``` file to 

```
  s.add_development_dependency "appraisal"
``` 

and I removed the ```gem "appraisal"``` that was in my Gemfile.

but unfortunately now I get ```File does not exist: minitest/rg```

did I miss something? My specs are written in Minitest. and they are all in ```test/lib/``` since they are all testing ```lib/``` code, I have four specs and they all end in ```_test.rb```. 

trying to figure out what I missed here.

```
$ bundle exec appraisal rake test
>> BUNDLE_GEMFILE=/Users/jason/Projects/nondestructive_migrations/nondestructive_migrations/gemfiles/rails_4_0.gemfile bundle exec rake test

File does not exist: minitest/rg

Run options: --seed 62304

# Running tests:



Finished tests in 0.000345s, 0.0000 tests/s, 0.0000 assertions/s.

0 tests, 0 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /Users/jason/Projects/nondestructive_migrations/nondestructive_migrations/coverage. 0 / 253 LOC (0.0%) covered.
rake aborted!
Command failed with status (1)
/Users/jason/.rvm/gems/ruby-2.2.5/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/jason/.rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:24:in `eval'
/Users/jason/.rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
Run options: --seed 2877

# Running tests:



Finished tests in 0.000358s, 0.0000 tests/s, 0.0000 assertions/s.

0 tests, 0 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by nickcharlton** [comment]
Were you able to solve this since then?

If not, can you point me to an example project I can try out? I'm not sure what to suggest quite yet.

**Comment by jasonfb** [comment]
I can't say for sure. I'm not 100% and I think I moved on so I will close
