### ISSUE TITLE
Cleaning up outdated lockfiles?

### ISSUE THREAD

**Issue by mvz** [thoughtbot/appraisal#153]
The README suggests not checking in the lockfiles. This means that when you update your local repo with latest remote master, your appraisal gemfiles may be updated, but the lockfiles contain different, incompatible versions, causing an error during `appraisal install`, e.g.:

```
You have requested:
  nokogiri < 1.9.1

The bundle currently has nokogiri locked at 1.10.2.
Try running `bundle update nokogiri`
```

Is there any way to force appraisal to re-generate the lockfiles in such a case?

**Comment by kbrock** [comment]
@mrz I tend to brute force it

```
appraisal clean
appraisal generate
```

**Comment by mvz** [comment]
@kbrock thanks, I'll try that.

**Comment by nickcharlton** [comment]
As an alternative option, I typically do `appraisal update` to solve this.
