### ISSUE TITLE
Circle CI caching

### ISSUE THREAD

**Issue by rpbaltazar** [thoughtbot/appraisal#175]
The recommendation suggests that we don't commit the gemfile locks to the repo. 
Circle caching suggestion is based on the checksum of the lockfile.

This way the cache will never work for the different appraisals.

Is there a recommended way of handling that?

**Comment by n-rodriguez** [comment]
> The recommendation suggests that we don't commit the gemfile locks to the repo.

Actually this has changed

**Comment by n-rodriguez** [comment]
https://github.com/rubygems/rubygems/issues/3372
