### ISSUE TITLE
CI: What comes after Travis?

### ISSUE THREAD

**Issue by olleolleolle** [thoughtbot/appraisal#188]
Hi, I'm a user, looking to use GitHub Actions with Appraisal, and I came looking here for... ideas.

Now, the CI of this project does not run, and will not, due to the service being shuttered.

Is there interest in using another service for it?

**Comment by moiristo** [comment]
I recently updated my `deep_cloneable` gem from Travis to GHA. I managed to replicate the setup I previously had in Travis using gemfile paths (as in the README) by creating a build matrix of rubies and appraisals:

https://github.com/moiristo/deep_cloneable/blob/master/.github/workflows/ruby.yml

Hope this helps for you!

**Comment by n-rodriguez** [comment]
Hi there! Any news ?

**Comment by nickcharlton** [comment]
I started looking into a GitHub Actions matrix earlier today: https://github.com/thoughtbot/appraisal/tree/nc-use-github-actions

Lots to go yet (as I write this, it won't pass once), but broadly what I'm aiming for. I'd like to test against a few versions of bundler too, but _soon_.

**Comment by pboling** [comment]
Working example of Appraisal & Combustion with a massive test matrix on Github Actions in my sanitize_email gem here: https://github.com/pboling/sanitize_email/commit/a9c1d9a11732b57e1b898e74516bbff36724ff97

* Ruby 2.3 - Ruby 3.3
* Rails 3.0 - Rails 7.1

**Comment by n-rodriguez** [comment]
Hi there! I've made a PR that integrates GithubActions https://github.com/thoughtbot/appraisal/pull/230
