### ISSUE TITLE
New release for `install_if` support

### ISSUE THREAD

**Issue by ngan** [thoughtbot/appraisal#190]
Hello, can we get a new release for https://github.com/thoughtbot/appraisal/commit/2f5be65b8e127bd602fd149f395f2f8fa50616a8? 🙏 Thank you!

**Comment by n-rodriguez** [comment]
Yes! please!

**Comment by nickcharlton** [comment]
Hi @ngan, thanks for opening this and sorry for taking a long time to respond.

It's on my list to do — I'm keen to resolve the recent bundler incompatibilities in #173 which is our main blocker to releasing first.
