### ISSUE TITLE
customize_gemfiles is documented and merged to main but not released

### ISSUE THREAD

**Issue by tatzsuzuki** [thoughtbot/appraisal#198]
customize_gemfiles is documented in README. However, I got `undefined method` when I used the function as it wasn't released. 
https://github.com/thoughtbot/appraisal#example-usage-1

Could you consider releasing it, please?

**Comment by joe-sharp** [comment]
@nickcharlton any chance we can get a release soon?

**Comment by nickcharlton** [comment]
Thanks for the ping!

Yes — I've just merged in #202 to fix #173 that I was hesitant to make a release without that particular issue resolved so in the next few days once I've tidied up a few more things.

**Comment by duffn** [comment]
This would be nice to have, thanks!
