### ISSUE TITLE
`bundle check` returning exit code 1 but gems don't get installed

### ISSUE THREAD

**Issue by nunommc** [thoughtbot/appraisal#211]
I've struggled a little bit to get appraisal to run the specs for [acts_as_tenant gem](https://github.com/ErwinM/acts_as_tenant).

See the output below. The command that took 7m 8s (top-right corner) was `bundle install` (most of the time "Resolving dependencies...")
![image](https://github.com/thoughtbot/appraisal/assets/4332567/ce2d7126-4e65-48e6-9bb6-04bed69bf286)

```
$ bundle exec appraisal install
>> bundle check --gemfile='/home/nuno/rails/gems/acts_as_tenant/gemfiles/rails_6_1.gemfile' || bundle install --gemfile='/home/nuno/rails/gems/acts_as_tenant/gemfiles/rails_6_1.gemfile' --retry 1
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/home/nuno/rails/gems/acts_as_tenant/gemfiles/rails_7.gemfile' || bundle install --gemfile='/home/nuno/rails/gems/acts_as_tenant/gemfiles/rails_7.gemfile' --retry 1
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/home/nuno/rails/gems/acts_as_tenant/gemfiles/sidekiq_7.gemfile' || bundle install --gemfile='/home/nuno/rails/gems/acts_as_tenant/gemfiles/sidekiq_7.gemfile' --retry 1
The Gemfile's dependencies are satisfied
```

Despite of the "The Gemfile's dependencies are satisfied" output, that didn't seem to be true, because by running each o the commands on the left-hand side of the OR operator it was returning an EXIT STATUS 1 (error).

![image](https://github.com/thoughtbot/appraisal/assets/4332567/8f7e1a72-adfc-42b7-b350-3bcca64186b5)

Then by running the 2nd part of the command manually (ie `bundle install --gemfile='/home/nuno/rails/gems/acts_as_tenant/gemfiles/rails_6_1.gemfile' --retry 1`) it installed the missing gems and I was then able to run the specs successfully.

I'm not too sure why "The Gemfile's dependencies are satisfied" is being printed when some gems are missing.

**Comment by nunommc** [comment]
I replaced the following in my Gemfile

I believe #176 fixed the issue above, as everything installed nicely after changing the following:

```diff
- gem "appraisal"
+ gem "appraisal", github: "thoughtbot/appraisal", branch: 'main'
```

Could you please publish a new version of this gem?

**Comment by nickcharlton** [comment]
Ah right, okay. I'm looking at cutting a new release today/tomorrow so I'll close this for now. Thanks for reporting.
