### ISSUE TITLE
undefined method `expand_path' for Appraisal::File:Class

### ISSUE THREAD

**Issue by ZenCocoon** [thoughtbot/appraisal#4]
I'm trying to add `Appraisal` to my branch of [rspec-core](https://github.com/ZenCocoon/rspec-core/tree/subject_each) however I get the following error.

Update: I use the github/master version as depending on aruba 0.4.2

    $ rake --trace
    rake aborted!
    undefined method `expand_path' for Appraisal::File:Class
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bundler/gems/appraisal-f8029181543b/lib/appraisal/gemfile.rb:22:in `block in run'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bundler/gems/appraisal-f8029181543b/lib/appraisal/gemfile.rb:21:in `each'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bundler/gems/appraisal-f8029181543b/lib/appraisal/gemfile.rb:21:in `run'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bundler/gems/appraisal-f8029181543b/lib/appraisal/gemfile.rb:18:in `instance_eval'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bundler/gems/appraisal-f8029181543b/lib/appraisal/gemfile.rb:18:in `run'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bundler/gems/appraisal-f8029181543b/lib/appraisal/gemfile.rb:14:in `load'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bundler/gems/appraisal-f8029181543b/lib/appraisal/file.rb:16:in `initialize'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bundler/gems/appraisal-f8029181543b/lib/appraisal/file.rb:10:in `new'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bundler/gems/appraisal-f8029181543b/lib/appraisal/file.rb:10:in `each'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bundler/gems/appraisal-f8029181543b/lib/appraisal/task.rb:30:in `block in initialize'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task_manager.rb:207:in `in_namespace'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/dsl_definition.rb:95:in `namespace'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bundler/gems/appraisal-f8029181543b/lib/appraisal/task.rb:9:in `initialize'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bundler/gems/appraisal-f8029181543b/lib/appraisal.rb:3:in `new'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bundler/gems/appraisal-f8029181543b/lib/appraisal.rb:3:in `<top (required)>'
    /Users/seb/Work/GitHub/rspec-core/Rakefile:5:in `require'
    /Users/seb/Work/GitHub/rspec-core/Rakefile:5:in `<top (required)>'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:495:in `raw_load_rakefile'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:78:in `block in load_rakefile'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:61:in `block in run'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bin/rake:19:in `load'
    /Users/seb/.rvm/gems/ruby-1.9.2-p180/bin/rake:19:in `<main>'

The idea of `Appraisal` is really awesome, thanks for this great work.

**Comment by schneems** [comment]
Was getting this

```
/Users/richardschneeman/.gem/ruby/2.2.3/gems/appraisal-2.1.0/lib/appraisal/gemfile.rb:26:in `run': undefined method `expand_path' for Appraisal::File:Class (NoMethodError)
	from /Users/richardschneeman/.gem/ruby/2.2.3/gems/appraisal-2.1.0/lib/appraisal/gemfile.rb:20:in `instance_eval'
	from /Users/richardschneeman/.gem/ruby/2.2.3/gems/appraisal-2.1.0/lib/appraisal/gemfile.rb:20:in `run'
	from /Users/richardschneeman/.gem/ruby/2.2.3/gems/appraisal-2.1.0/lib/appraisal/gemfile.rb:15:in `load'
	from /Users/richardschneeman/.gem/ruby/2.2.3/gems/appraisal-2.1.0/lib/appraisal/file.rb:17:in `initialize'
	from /Users/richardschneeman/.gem/ruby/2.2.3/gems/appraisal-2.1.0/lib/appraisal/file.rb:11:in `new'
	from /Users/richardschneeman/.gem/ruby/2.2.3/gems/appraisal-2.1.0/lib/appraisal/file.rb:11:in `each'
	from /Users/richardschneeman/.gem/ruby/2.2.3/gems/appraisal-2.1.0/lib/appraisal/task.rb:32:in `block in initialize'
	from /Users/richardschneeman/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task_manager.rb:209:in `in_namespace'
	from /Users/richardschneeman/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/dsl_definition.rb:147:in `namespace'
	from /Users/richardschneeman/.gem/ruby/2.2.3/gems/appraisal-2.1.0/lib/appraisal/task.rb:9:in `initialize'
	from /Users/richardschneeman/.gem/ruby/2.2.3/gems/appraisal-2.1.0/lib/appraisal.rb:4:in `new'
	from /Users/richardschneeman/.gem/ruby/2.2.3/gems/appraisal-2.1.0/lib/appraisal.rb:4:in `<top (required)>'
	from /Users/richardschneeman/.gem/ruby/2.2.3/gems/appraisal-2.1.0/bin/appraisal:4:in `require'
	from /Users/richardschneeman/.gem/ruby/2.2.3/gems/appraisal-2.1.0/bin/appraisal:4:in `<top (required)>'
	from /Users/richardschneeman/.gem/ruby/2.2.3/bin/appraisal:23:in `load'
	from /Users/richardschneeman/.gem/ruby/2.2.3/bin/appraisal:23:in `<main>'
```

It's unclear that this was coming from my main Gemfile. Is there any way we can maybe rescue syntax errors and re-raise them with the thing that Appraisal is currently instance eval-ing?

**Comment by sikachu** [comment]
There are two parts to this problem.

* I feel like it's not _your_ fault though. You probably did `File.expand_path` which is super legit in your Gemfile. I think this `Appraisal::File` name choice starting to be a bad thing.
* I agree that when there's a syntax error it should re-raising. I'm not sure what currently going to happen if you have a syntax error, but will investigate to make sure that the proper error is printed out.

I'm reopening this to fix the issue on the first bullet point. @jferris, do you think it's better idea to just rename `Appraisal::File` -> `Appraisal::AppraisalFile` or something like that to free up `File` constant?

**Comment by sikachu** [comment]
This should be fixed in the next patch version. Thank you for your patience!
