### ISSUE TITLE
Dependency conflict

### ISSUE THREAD

**Issue by smartinez87** [thoughtbot/appraisal#75]
I'm getting the following conflict when trying to bundle.
Is there a chance to not fix the version of thor in [this](https://github.com/thoughtbot/appraisal/blob/master/Gemfile#L5) line?
```
Bundler could not find compatible versions for gem "thor":
  In Gemfile:
    rails (~> 4.0) ruby depends on
      thor (< 2.0, >= 0.18.1) ruby

    appraisal (~> 1.0) ruby depends on
      thor (0.15.4)
```

**Comment by sikachu** [comment]
Ping @smartinez87, are you still seeing this issue?

**Comment by sikachu** [comment]
Closing this as stale.
