### ISSUE TITLE
Appraisal doesn't support gemspec inside group

### ISSUE THREAD

**Issue by maxlinc** [thoughtbot/appraisal#76]
# Overview

Although Appraisal does support gemspec (https://github.com/thoughtbot/appraisal/issues/48) and other Bundler DSL methods, there are some discrepancies in where the gemspec method is allowed.

I'd like to use Appraisal to test a vagrant plugin against multiple releases of Vagrant. Vagrant and Vagrant plugins are just gems, but Vagrant plugin development follows less common Gemfile conventions that don't seem to work with Appraisal.

# Background

This is a brief explanation of how Vagrant and Vagrant plugin installs work, and why that's resulted in unusual Gemfile conventions. If you don't care why Vagrant plugins use special bundler groups than you can skip to the next section. Nothing in this section needs to be supported by Appraisal.

Vagrant is [no longer distributed via RubyGems](http://mitchellh.com/abandoning-rubygems). Instead, it's distributed via native package installers that include an embedded Ruby, so Vagrant has more control over non-Ruby dependencies (e.g. Virtualbox) and is easy to install for non-Ruby users. This also means plugins are installed to the embedded ruby with `vagrant plugin install` rather than `gem install` or `bundle install`.

The result is that Gemfiles for Vagrant development follow different conventions than many Ruby projects:

- The plugin's gemspec should not depend on Vagrant since it won't be installed as a gem.
- The plugins Gemfile should depend on Vagrant, but using a git branch/tag rather than a RubyGem release
- Any plugins (including the plugin under development) should be put into a special bundler group called "plugins" so Vagrant can detect and auto-load them the same way it would plugins that had been installed via `vagrant plugin install`.

# Examples

## Appraisals file

I would like to use these Appraisals:

```ruby
appraise "latest-stable" do
  group :development do
    gem "vagrant", :git => 'git://github.com/mitchellh/vagrant.git', :branch => 'v1.4.2'
  end
end

# Oldest (current release)
appraise "oldest-current" do
  group :development do
    gem "vagrant", :git => 'git://github.com/mitchellh/vagrant.git', :branch => 'v1.4.0'
  end
end

# Latest patch (previous release)
appraise "previous-release" do
  group :development do
    gem "vagrant", :git => 'git://github.com/mitchellh/vagrant.git', :branch => 'v1.3.5'
  end
end

appraise "windows-wip" do
  group :development do
    gem "vagrant", :git => 'git://github.com/maxlinc/vagrant.git', :branch => 'winrmssl'
  end
end
```

That will test my plugin the last several releases of Vagrant, as well as a fork where new features are being added for Windows.

Appraisal actually overrides the vagrant dependencies properly. It has an issue with the gem under development.

## Approach 1 - gemspec

This is what I have in my Gemfile:

```ruby
source 'https://rubygems.org'

group :development do
  gem "vagrant", git: "https://github.com/mitchellh/vagrant.git"
  gem 'appraisal', '~> 1.0'
end

group :plugins do
  gemspec
end
```

This doesn't work, because although Appraisal handles the gemspec method it doesn't seem to allow it within a group:

```
$ bundle exec appraisal install
/opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal/gemfile.rb:39:in `block in run': undefined local variable or method `gemspec' for #<Appraisal::Group:0x007fb09c299c40> (NameError)
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal/group.rb:12:in `instance_exec'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal/group.rb:12:in `run'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal/gemfile.rb:38:in `group'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal/gemfile.rb:38:in `run'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal/gemfile.rb:29:in `instance_eval'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal/gemfile.rb:29:in `run'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal/gemfile.rb:25:in `load'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal/file.rb:17:in `initialize'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal/file.rb:11:in `new'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal/file.rb:11:in `each'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal/task.rb:32:in `block in initialize'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task_manager.rb:209:in `in_namespace'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/dsl_definition.rb:146:in `namespace'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal/task.rb:9:in `initialize'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal.rb:4:in `new'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/lib/appraisal.rb:4:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/bin/appraisal:4:in `require'
	from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/appraisal-1.0.2/bin/appraisal:4:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.1.0/bin/appraisal:23:in `load'
	from /opt/boxen/rbenv/versions/2.1.0/bin/appraisal:23:in `<main>'
```

## Approach 2 - gem with path

Alternately, the vagrant plugin development guide uses `gem "my-plugin", path: "."` instead of `gemspec`.

```ruby
source 'https://rubygems.org'

group :development do
  gem "vagrant", git: "https://github.com/mitchellh/vagrant.git"
  gem 'appraisal', '~> 1.0'
end

group :plugins do
  gem "vagrant-rackspace", path: "."
end
```

This doesn't work either, probably because support for rewriting path wasn't completed/merged (https://github.com/thoughtbot/appraisal/pull/19). The result:

```
$ bundle exec appraisal install
bundle check --gemfile='/Users/Thoughtworker/repos/rackspace/vagrant-rackspace/gemfiles/latest_stable.gemfile' || bundle install --gemfile='/Users/Thoughtworker/repos/rackspace/vagrant-rackspace/gemfiles/latest_stable.gemfile'
Resolving dependencies...
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Could not find gem 'vagrant-rackspace (>= 0) ruby' in source at ..
Source does not contain any versions of 'vagrant-rackspace (>= 0) ruby'
```

**Comment by sikachu** [comment]
I've extracted the `:path` problem to #82. This issue will focus on making `gemspec` works in `group`.
