### ISSUE TITLE
DSL aliases mixed up?

### ISSUE THREAD

**Issue by maxlinc** [thoughtbot/appraisal#78]
It seems like the aliases were swapped unless the bundler DSL used to be different.

In the [Bundler DSL](http://www.rubydoc.info/github/bundler/bundler/Bundler/Dsl):
- `#platforms` is aliased as `#platform`
- `#group` does not have an alias

In the Appraisal DSL:
- `#group` is aliased as `#groups`
- `#platform` does not have an alias

**Comment by sikachu** [comment]
Good catch. Seems to be a quick fix, so let me do that.

Note that we'll have to maintain `groups` until we're shipping 2.0 though. So I'll keep this open until then.

**Comment by sikachu** [comment]
Actually, I made #83 to take care of removal. Let's just make sure we have `platforms` here.

**Comment by sikachu** [comment]
Thanks for reporting!
