### ISSUE TITLE
Not supported on ruby 1.8.7 ?

### ISSUE THREAD

**Issue by fcastellanos** [thoughtbot/appraisal#90]
I'm trying to test a gem that I'm building under at lease two ruby versions, 1.8.7 and 2.1.x, when I switch to ruby 1.8.7 I could do bundle install successfully but when I do 

    $ appraisal ruby-1.8.7-p352 rspec

I get a SyntaxError

    /Users/fcastellanos/.rvm/gems/ruby-1.8.7-p352/gems/appraisal-1.0.3/lib/appraisal/file.rb:1:in `require': /Users/fcastellanos/.rvm/gems/ruby-1.8.7-p352/gems/appraisal-1.0.3/lib/appraisal/appraisal.rb:68: syntax error, unexpected ':', expecting ')' (SyntaxError)
      Command.new(command, env: env).run
                               ^

Am I doing something wrong or ruby 1.8.7 is not supported?

Thanks

**Comment by sikachu** [comment]
Ruby 1.8.7 is currently not supported. I started porting a patch from #89 and it seems like there're still lots of stuff that needs to be fixed. I think it's going to take a bit of time.

I'm going go close this in favor of #89. You can track the progress there.

**Comment by sikachu** [comment]
I merge #89 and eb7e0f28f30b9543510d258261dae207fb162f5d in, so Appraisal should now work with Ruby 1.8.7.
