### ISSUE TITLE
Remove the activesupport production dependency

### ISSUE THREAD

**Issue by nbibler** [thoughtbot/appraisal#94]
A recent change to [add Ruby 1.8 support](https://github.com/thoughtbot/appraisal/commit/eb7e0f28f30b9543510d258261dae207fb162f5d) to Appraisal forced "activesupport" to be `">= 3.2.21"`. This now disallows developers to use Appraisal to test against any Rails (or activesupport) version prior to 3.2.21.

Previously, the Appraisal activesupport dependency was a development dependency. As such, the generated Appraisal Gemfiles within a project did not inject their own activesupport dependency.

The move to making activesupport a production dependency significantly reduces Appraisal's usefulness as now all appraisals have to have activesupport >= 3.2.21.

**Comment by sikachu** [comment]
Agreed. We pretty much just need to port `OrderedHash` from Active Support and then we can be freed from it.

If you have some time, it'd be awesome if you can help me submit a patch to clone that in. If not, I think I can get to it within this month.

Thanks for your bug report!

**Comment by nbibler** [comment]
Yeah, I think I can get it done. It doesn't look like it should be that big of a change.

**Comment by nbibler** [comment]
I think the referenced PR fixes the issue... let us know if you have any thoughts or issues with it.

**Comment by sikachu** [comment]
@nbibler I didn't have time to review the PR, sorry about that. I'm looking at this now.

**Comment by nbibler** [comment]
:+1: Thanks @sikachu and @omghax !
