### ISSUE TITLE
install hints at --travis option which doesn't work

### ISSUE THREAD

**Issue by gtd** [thoughtbot/appraisal#97]
first:

```
bundle exec appraisal install
=> Note: Run with --travis to generate Travis CI configuration.
=> ....
```

but then:

```
bundle exec appraisal install --travis
=> ERROR: "appraisal install" was called with arguments ["--travis"]
=> Usage: "appraisal install"
```

**Comment by sikachu** [comment]
Oh. It's because the correct command is actually `appraisal generate --travis`. However, because `install` actually runs `generate` internally, you are getting that warning as well.

I'll look into this. Thanks for reporting.

**Comment by sikachu** [comment]
I changed the warning message. Thank you for reporting this in.
